# Generated by Django 5.0.1 on 2024-06-06 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('quantity', models.CharField(max_length=50)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('product_catogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product_image/')),
                ('active', models.BooleanField(default=True)),
                ('single_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.product')),
            ],
        ),
    ]
