# Generated by Django 5.0.1 on 2024-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
