# Generated by Django 5.0.1 on 2024-06-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_alter_product_long_description_alter_sign_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
